name: Setup just
description: Install a pinned version of just for charmed-hpc CI

inputs:
  just-version:
    description: Override the default just version
    required: false
    default: "1.48.1"

runs:
  using: composite
  steps:
    - uses: extractions/setup-just@v4
      with:
        just-version: ${{ inputs.just-version }}
