name: CI
on:
  workflow_call:
  pull_request:

jobs:
  ci:
    uses: ./.github/workflows/charmed-hpc-ci.yaml
    with:
      run-test: false
      setup-commands: sudo snap install opentofu --classic --channel latest/stable
